#!/bin/sh
MODEL_FILE="/Users/ahasan/Documents/seismology_software/PROJECTFFT7/OBSDIR/SCM.mod"

hrftn96 -M "$MODEL_FILE" -RAYP 0.07 -DT 0.05 -NPTS 2048 -P -z
mv hrftn96.sac "OBS_Z.sac"

hrftn96 -M "$MODEL_FILE" -RAYP 0.07 -DT 0.05 -NPTS 2048 -P -r
mv hrftn96.sac "OBS_R.sac"

